// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AppConfig {
    "openai_key": string;
    "whisper_model": string;
    "whisper_language": string;
    "download_dir": string;

    /** Creates a new AppConfig instance. */
    constructor($$source: Partial<AppConfig> = {}) {
        if (!("openai_key" in $$source)) {
            this["openai_key"] = "";
        }
        if (!("whisper_model" in $$source)) {
            this["whisper_model"] = "";
        }
        if (!("whisper_language" in $$source)) {
            this["whisper_language"] = "";
        }
        if (!("download_dir" in $$source)) {
            this["download_dir"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): AppConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppConfig($$parsedSource as Partial<AppConfig>);
    }
}

export class TaskPo {
    "id": number;
    "task": string;
    "video_url": string;
    "task_status": string;
    "created_at": number;
    "updated_at": number;

    /** Creates a new TaskPo instance. */
    constructor($$source: Partial<TaskPo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("task" in $$source)) {
            this["task"] = "";
        }
        if (!("video_url" in $$source)) {
            this["video_url"] = "";
        }
        if (!("task_status" in $$source)) {
            this["task_status"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = 0;
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TaskPo instance from a string or object.
     */
    static createFrom($$source: any = {}): TaskPo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TaskPo($$parsedSource as Partial<TaskPo>);
    }
}
