// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "./internal/model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../wailsapp/wails/v3/pkg/application/models.js";

export function AddTask(videoUrl: string): $CancellablePromise<void> {
    return $Call.ByID(36020417, videoUrl);
}

export function DeleteTask(id: number): $CancellablePromise<void> {
    return $Call.ByID(295530199, id);
}

export function DownloadVideo(url: string): $CancellablePromise<string> {
    return $Call.ByID(3488628824, url);
}

export function GetConfig(): $CancellablePromise<model$0.AppConfig> {
    return $Call.ByID(1058182565).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetTasks(): $CancellablePromise<model$0.TaskPo[]> {
    return $Call.ByID(2281281863).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * OnStartup is called when the service starts
 */
export function OnStartup(options: application$0.ServiceOptions): $CancellablePromise<void> {
    return $Call.ByID(2359339329, options);
}

export function OpenDownloadDir(): $CancellablePromise<string> {
    return $Call.ByID(1527975828);
}

export function OpenSettingsWindow(): $CancellablePromise<void> {
    return $Call.ByID(1367546872);
}

export function OrganizeContent(content: string): $CancellablePromise<string> {
    return $Call.ByID(3597130505, content);
}

/**
 * SetApp sets the application instance (called from main after app creation)
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(2528128870, app);
}

export function TranscribeAudio(audioPath: string): $CancellablePromise<string> {
    return $Call.ByID(1291854384, audioPath);
}

export function UpdateConfig(newConfig: model$0.AppConfig): $CancellablePromise<void> {
    return $Call.ByID(2002504706, newConfig);
}

// Private type creation functions
const $$createType0 = model$0.AppConfig.createFrom;
const $$createType1 = model$0.TaskPo.createFrom;
const $$createType2 = $Create.Array($$createType1);
