// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function DownloadVideo(arg1:string):Promise<string>;

export function GetConfig():Promise<config.AppConfig>;

export function OrganizeContent(arg1:string):Promise<string>;

export function TranscribeAudio(arg1:string):Promise<string>;

export function UpdateConfig(arg1:config.AppConfig):Promise<void>;
