// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function AddTask(arg1:string):Promise<void>;

export function DeleteTask(arg1:number):Promise<void>;

export function DownloadVideo(arg1:string):Promise<string>;

export function GetConfig():Promise<model.AppConfig>;

export function GetTasks():Promise<Array<model.TaskPo>>;

export function OpenDownloadDir():Promise<string>;

export function OrganizeContent(arg1:string):Promise<string>;

export function TranscribeAudio(arg1:string):Promise<string>;

export function UpdateConfig(arg1:model.AppConfig):Promise<void>;
