// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTask(arg1) {
  return window['go']['main']['App']['AddTask'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function DownloadVideo(arg1) {
  return window['go']['main']['App']['DownloadVideo'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetTasks() {
  return window['go']['main']['App']['GetTasks']();
}

export function OpenDownloadDir() {
  return window['go']['main']['App']['OpenDownloadDir']();
}

export function OrganizeContent(arg1) {
  return window['go']['main']['App']['OrganizeContent'](arg1);
}

export function TranscribeAudio(arg1) {
  return window['go']['main']['App']['TranscribeAudio'](arg1);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}
